export const rawDataTableData = [
  {
    id: 1,
    name: "Humfrey Scain",
    position: "Construction Foreman",
    office: "Micheng",
    age: 40,
    start_date: "08/10/2023",
    salary: "150,000",
  },
  {
    id: 2,
    name: "Jeane Sherland",
    position: "Electrician",
    office: "Donskoye",
    age: 38,
    start_date: "12/12/2023",
    salary: "140,000",
  },
  {
    id: 3,
    name: "Merrie Van Son",
    position: "Construction Worker",
    office: "Yanqul",
    age: 37,
    start_date: "30/06/2023",
    salary: "110,000",
  },
  {
    id: 4,
    name: "Myrtia Fitchell",
    position: "Project Manager",
    office: "Mabuttal East",
    age: 35,
    start_date: "09/04/2024",
    salary: "110,000",
  },
  {
    id: 5,
    name: "Betty Giannotti",
    position: "Construction Worker",
    office: "Hetang",
    age: 30,
    start_date: "10/02/2024",
    salary: "140,000",
  },
  {
    id: 6,
    name: "Alfy Kirimaa",
    position: "Estimator",
    office: "Esquipulas",
    age: 27,
    start_date: "05/08/2023",
    salary: "95,000",
  },
  {
    id: 7,
    name: "Arte Gledhall",
    position: "Construction Manager",
    office: "Yabrūd",
    age: 28,
    start_date: "23/04/2023",
    salary: "90,000",
  },
  {
    id: 8,
    name: "Ardene Beckensall",
    position: "Supervisor",
    office: "Thị Trấn Thanh Lưu",
    age: 26,
    start_date: "07/08/2023",
    salary: "100,000",
  },
  {
    id: 9,
    name: "Allsun Johnstone",
    position: "Project Manager",
    office: "Liujiage",
    age: 29,
    start_date: "15/07/2023",
    salary: "80,000",
  },
  {
    id: 10,
    name: "Leigha Tattersill",
    position: "Estimator",
    office: "Libao",
    age: 29,
    start_date: "02/06/2023",
    salary: "80,000",
  },
];
